# Generated by Django 4.1.1 on 2022-11-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address_line',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='userprofile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
