# Generated by Django 4.1.1 on 2022-10-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_rating',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/Review_image'),
        ),
    ]
